# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S5cmd < Formula
  desc "Parallel S3 and local filesystem execution tool"
  homepage "https://github.com/peak/s5cmd"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peak/s5cmd/releases/download/v2.1.0/s5cmd_2.1.0_macOS-64bit.tar.gz"
      sha256 "096a6dc9047855a16b266868bedd9bd89370e5c64763ad3fe4d436c85b7fec3c"

      def install
        bin.install "s5cmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peak/s5cmd/releases/download/v2.1.0/s5cmd_2.1.0_macOS-arm64.tar.gz"
      sha256 "1638d9497cfe3133fa0a83c3c618f5cefddab099810f40dd9174640ecff1a952"

      def install
        bin.install "s5cmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/peak/s5cmd/releases/download/v2.1.0/s5cmd_2.1.0_Linux-64bit.tar.gz"
      sha256 "5f3e6abbb0d71fba1cf2c7884635828af3d151c4795d0d1827f623e2f52bfab0"

      def install
        bin.install "s5cmd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peak/s5cmd/releases/download/v2.1.0/s5cmd_2.1.0_Linux-arm64.tar.gz"
      sha256 "6eef03a90853fb0ad12237e912031af033b3312e4d340c0e40923a991e988142"

      def install
        bin.install "s5cmd"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/peak/s5cmd/releases/download/v2.1.0/s5cmd_2.1.0_Linux-armv6.tar.gz"
      sha256 "7d351296e28999321a6d1325118dc448e7a099964d312363005e48be984c1aff"

      def install
        bin.install "s5cmd"
      end
    end
  end

  test do
    system "#{bin}/s5cmd version"
  end
end
