# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S5cmd < Formula
  desc "Parallel S3 and local filesystem execution tool"
  homepage "https://github.com/peak/s5cmd"
  version "2.0.0-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peak/s5cmd/releases/download/v2.0.0-beta/s5cmd_2.0.0-beta_macOS-64bit.tar.gz"
      sha256 "6bce01dae890c530f86046c24297beb91eb050ca80f825e05729b035b998c522"

      def install
        bin.install "s5cmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peak/s5cmd/releases/download/v2.0.0-beta/s5cmd_2.0.0-beta_macOS-arm64.tar.gz"
      sha256 "5f0b3d9dec632c58c2db796742e44aabd8b9b871cea5e2577e671b7a27908efa"

      def install
        bin.install "s5cmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/peak/s5cmd/releases/download/v2.0.0-beta/s5cmd_2.0.0-beta_Linux-64bit.tar.gz"
      sha256 "16a1ffd5b00d56e1d7ee0f2f4cbc4a435e78113ebba4235986a43bf47c02a629"

      def install
        bin.install "s5cmd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peak/s5cmd/releases/download/v2.0.0-beta/s5cmd_2.0.0-beta_Linux-arm64.tar.gz"
      sha256 "68f8cdc43f0bf95ad1e5cb36a3ee1cacfe0bdc481965cc1f2e267ef3d981ee2b"

      def install
        bin.install "s5cmd"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/peak/s5cmd/releases/download/v2.0.0-beta/s5cmd_2.0.0-beta_Linux-armv6.tar.gz"
      sha256 "b7a5e6b7d9b8355a6ea165aeb86fde3e717b536eb7e4be935695dccca479910a"

      def install
        bin.install "s5cmd"
      end
    end
  end

  test do
    system "#{bin}/s5cmd version"
  end
end
