# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S5cmd < Formula
  desc "Parallel S3 and local filesystem execution tool"
  homepage "https://github.com/peak/s5cmd"
  version "2.1.0-beta.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/peak/s5cmd/releases/download/v2.1.0-beta.1/s5cmd_2.1.0-beta.1_macOS-arm64.tar.gz"
      sha256 "4bf98bce34bb8dec5b3646bc33dc71100f0e8fd6f35f0ec75fbc4836869c07fe"

      def install
        bin.install "s5cmd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/peak/s5cmd/releases/download/v2.1.0-beta.1/s5cmd_2.1.0-beta.1_macOS-64bit.tar.gz"
      sha256 "d23371ecd3b581409d05fc1289efa321ecb7065ca8b5197fe7c9d767dc4e1c29"

      def install
        bin.install "s5cmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/peak/s5cmd/releases/download/v2.1.0-beta.1/s5cmd_2.1.0-beta.1_Linux-armv6.tar.gz"
      sha256 "4748b2465ad12a28f195c5d2c2bf8eb7e1e1784a7061f263f57082ed4ba1602b"

      def install
        bin.install "s5cmd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peak/s5cmd/releases/download/v2.1.0-beta.1/s5cmd_2.1.0-beta.1_Linux-arm64.tar.gz"
      sha256 "f64dcaabbb837ce223d716c9e64b4829e5cd780f151a42f2d2cb7edccedb7b06"

      def install
        bin.install "s5cmd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/peak/s5cmd/releases/download/v2.1.0-beta.1/s5cmd_2.1.0-beta.1_Linux-64bit.tar.gz"
      sha256 "de5efa37941ef83e892662aefc936603a1a8acbc5a6a9e003a71721a7140b610"

      def install
        bin.install "s5cmd"
      end
    end
  end

  test do
    system "#{bin}/s5cmd version"
  end
end
